#include "includes/test.hpp"#include <iostream>#include <cdt/core/StringUtils.hpp>namespace cdt {void run_test(const std::vector<cdt::TestCase>* testcaseList) {	int total = 0;	int failCount = 0;	int successCount = 0;	for (const cdt::TestCase &testcase : *testcaseList) {		total++;		int totalRun = 0;		int errorNbr = 0;		int successNbr = 0;		std::cout << STR_CENTER(" " + testcase.desc + " ", '=', 79) << std::endl;		for (const cdt::Test &test : testcase.testList) {			try {				totalRun++;				std::cout << STR_PAD_RIGHT("   " + test.desc, '.', 64);				testcase.beforeEach();				test.test();				testcase.afterEach();				std::cout << STR_PAD_LEFT("OK   ", '.', 15) << std::endl;				successNbr++;			} catch (cdt::TestException e) {				std::cout << STR_PAD_LEFT("Test Fail   ", '.', 15) << std::endl;//				std::cout << e.getFile() << ":" << e.getLine() << std::endl;				std::cout << e.formatedMsg() << std::endl;				errorNbr++;			} catch (std::exception e) {				std::cout << STR_PAD_LEFT("Error   ", '.', 15) << std::endl;				std::cout << "   " << e.what() << std::endl;				errorNbr++;			} catch (...) {				std::cout << STR_PAD_LEFT("Error   ", '.', 15) << std::endl;				std::cout << "   " << "Unknown exception" << std::endl;				errorNbr++;			}		}		if (errorNbr == 0) {			successCount++;		} else {			failCount++;		}		std::stringstream ss;		ss << "Run: " << totalRun << ", Success: " << successNbr << ", Errors: " << errorNbr;		std::cout << STR_CENTER(" " + ss.str() + " ", '=', 79) << std::endl;		std::cout << std::endl;	}	std::cout << STR_CENTER(" Tests results ", '=', 79) << std::endl;	std::cout << STR_PAD_LEFT("Total tests:   ", ' ', 20) << total << std::endl;	std::cout << STR_PAD_LEFT("Total success: ", ' ', 20) << successCount << std::endl;	std::cout << STR_PAD_LEFT("Total fail:    ", ' ', 20) << failCount << std::endl;}} // namespace cdt